# 内部转发请求配置，0值为无超时 单位为秒
# connTimeout: 用户连接超时
# idleConnTimeout: 空闲连接超时
# responseHeaderTimeout: 响应头超时
server-conn:
  connTimeout: 0
  idleConnTimeout: 0
  responseHeaderTimeout: 0

white-addr:
#  - '127.0.0.1'
#  - 'xxx.xxx.xxx.xxx'

# 开启特殊标记增强
flags: true

# 图片访问
domain: "https://chat-completion-chatgpt-adapter.hf.space"

# 内调llm，用于绘图时文本转tags
llm:
  baseUrl: "http://127.0.0.1:7860"
  model: "bing"
  token: "xxx"

# lmsys fn、 trigger
lmsys: [49 , 109]

# hf 绘图接口配置化
# 若旧接口不可用，可以到huggingface上查找同类型的接口配置
# 参数替换：{{prompt}}、{{negative_prompt}}、{{sampler}}、{{style}}、{{seed}}
hf:
#  animagine-xl-3.1:
#    baseUrl: https://boboiazumi-animagine-xl-3-1.hf.space
#    fn: [5, 61]
#    data: '[
#      "{{prompt}}",
#      "{{negative_prompt}}",
#      {{seed}},
#      1024,
#      1024,
#      8,
#      35,
#      "{{sampler}}",
#      "1024 x 1024",
#      "{{style}}",
#      "Standard v3.1",
#      true,
#      0.55,
#      1.5,
#      false,
#      false,
#      null,
#      0.65
#    ]'
#  dalle-4k:
#    baseUrl: https://mukaist-dalle-4k.hf.space
#  dalle-3-xl:
#    baseUrl: https://ehristoforu-dalle-3-xl-lora-v2.hf.space

# gemini 自定义安全设置
google:
#  safes:
#    - category: HARM_CATEGORY_HARASSMENT
#      threshold: BLOCK_NONE

bing:
  baseUrl: "https://edgeservices.bing.com/edgesvc"

claude:
  pad: 0
  cookies:
    - 'xxx1'
    - 'xxx2'

you:
  helper: 8082
  notice: "Creative Writing Mode"
  cookies:
    -  'uuid_guest=87553351-ec24-4049-a616-79596b33bb6d; uuid_guest_backup=87553351-ec24-4049-a616-79596b33bb6d; safesearch_guest=Moderate; cf_chl_rc_m=1; ai_model=gpt_4o; youchat_personalization=true; youchat_smart_learn=true; daily_query_date=Mon%20Oct%2014%202024; AF_DEFAULT_MEASUREMENT_STATUS=true; afUserId=c44f12fb-92b2-417f-a943-5c32a47687b6-p; AF_SYNC=1728896288400; guest_has_seen_legal_disclaimer=true; _clck=aztk83%7C2%7Cfq0%7C0%7C1748; _gcl_au=1.1.1130381513.1728896887; _ga=GA1.1.1154706440.1728896887; FPID=FPID2.2.2oXVJoFMt16QRajSXJFyUninflSA%2FJwHqYywNZbcbhg%3D.1728896887; FPLC=P%2FpiaEfDwNgGQDJTQ8J2VlQg%2FkFDtuR9RVE6%2BnOwEoL41t0SCtGb93xeZgWZRDd8g5GX%2FNbAsWDOn6xW7g%2Flf222vtW3mU7TEV5ev9ELE44Y1sZpQEJi3FRJBDj%2BRA%3D%3D; FPAU=1.1.1130381513.1728896887; daily_query_count=5; cf_clearance=A1ImL65aJ4eWcHzhKoWEViLFGU5um45ofTsix3VJmII-1728897052-1.2.1.1-cG5NQhehTt8y4gB.LHaKzFQn7QG9dM0Lah8N0Z39ZAFOwdWxVaxe0idh9roSFKaZ_EM3FbJfj8yLjcS6WbQ8GRNxK0SWHcpnm_pqzuKRWBIqubTOQtAMeEqoqZcUCpzgwnQ0.Ur07_bZFCfOxKiOBHYaRJU1qvnE9UEQ.dTZnQznu_U6yQda5w26VeQ1Z0vgSP0G8H9E9UkXAPDvCEPuEOgwpYLMnCftQlqa174u_.5Dx7dh4og_mmJ6LsIKXjCEUv7zM.nUv9GRzciXARYEQmI0oR6xUcxOClEtT9TKkn0T6snvvULBF4vDkHg.a1h7RA8bvlNShq2dKDLcGSwwzB0coYYpLKU6tNWah2hraWh8MV8Ym5ZDWlyg3AuQ2HigByuNVm.tJdFX8wY5DVkBjg; total_query_count=7; FPGSID=1.1728896887.1728897888.G-WYGVQX1R23.4qP0aSNBclOTVV8ONtGzmA; _gtmeec=eyJlbSI6IjBjODFhYTA2MDRkOWRjYjg2YmZhOTYxYmIxYTQ1NDQ2ZTIzZTAwOGIxYTkyOTc2NzNhMmVmZDkzY2IxN2Y0YmMiLCJjdCI6ImFmZTA0NTc5MDA0MDQ5Y2NjZTE4NDNhNDBiZGY5ZWI4NWYzYTQ4MzkzOTAzNzVlMzVkMDAxOGE3ZjlhYTcwYzgiLCJzdCI6IjNmZGJhMzVmMDRkYzhjNDYyOTg2Yzk5MmJjZjg3NTU0NjI1NzExMzA3MmE5MDljMTYyZjdlNDcwZTU4MWUyNzgiLCJ6cCI6IjEwNjJhMThiMjE3MTQwZTMyMDQ2NzI0YjYyOWQwOWY2ZmU5MGNiZDk1YjBjZjE5MGQ4MmY0MzNiYzlmYWQyNmUiLCJjb3VudHJ5IjoiOTczMmM4M2UzZTAzZmZmZGUyZWU2NWE5ZDgyNmRmOGM0ZGQ2MjNjMjdmYjkyYjk1MmZlNjJhMDJmMDcyNmY4NyJ9; ld_context=%7B%22kind%22%3A%22user%22%2C%22key%22%3A%2287553351-ec24-4049-a616-79596b33bb6d%22%2C%22email%22%3A%223769mechanical%40rustyload.com%22%2C%22country%22%3A%22JP%22%2C%22userAgent%22%3A%22Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F129.0.0.0%20Safari%2F537.36%20Edg%2F129.0.0.0%22%2C%22secUserAgent%22%3A%22%5C%22Microsoft%20Edge%5C%22%3Bv%3D%5C%22129%5C%22%2C%20%5C%22Not%3DA%3FBrand%5C%22%3Bv%3D%5C%228%5C%22%2C%20%5C%22Chromium%5C%22%3Bv%3D%5C%22129%5C%22%22%7D; youpro_subscription=false; _clsk=qmqfvx%7C1728897957440%7C29%7C1%7Cw.clarity.ms%2Fcollect; DSR=eyJhbGciOiJSUzI1NiIsImtpZCI6IlNLMmpJbnU3SWpjMkp1eFJad1psWHBZRUpQQkFvIiwidHlwIjoiSldUIn0.eyJhbXIiOlsiZW1haWwiXSwiYXV0aDBJZCI6bnVsbCwiZHJuIjoiRFNSIiwiZW1haWwiOiIzMG1lbGluYUBydXN0eWxvYWQuY29tIiwiZXhwIjoxNzYwMzQ3NTg4LCJnaXZlbk5hbWUiOiIiLCJpYXQiOjE3Mjg4OTc5ODgsImlzcyI6IlAyakludHRSTXVYcHlZWk1iVmNzYzRDOVowUlQiLCJsYXN0TmFtZSI6IiIsIm5hbWUiOiIiLCJwaWN0dXJlIjoiIiwic3R5dGNoSWQiOm51bGwsInN1YiI6IlUyblFHZlBiZWZ6TXpkV0J1aXA1OWg2RUlNQ2UiLCJ0ZW5hbnRJbnZpdGF0aW9uIjpudWxsLCJ0ZW5hbnRJbnZpdGVyIjpudWxsLCJ1c2VySWQiOiJVMm5RR2ZQYmVmek16ZFdCdWlwNTloNkVJTUNlIiwidmVyaWZpZWRFbWFpbCI6dHJ1ZX0.YXwo1-Vx-2HOxKGqho-AYKpCGkpW5hROqWuQVDM2ILEGqCIo9bPAXXDx_vJzkXBKmZcftVmkdFXILGNTCaWOdgiu24RpMAMzpUE7zMmNehY5byW0v6miwJiyJmg_Fp3Qdyx8RF5OLm5jjm_5fi4aodJrZD2XRDMtU8zW9mdhAyaG6Ot01nJ57kbfYYJGLnl5aiLxupzzAN57s0b5OrOXKMDCn0wCy4HU2neBf7Zp9fMAAUZokbnEfcuyF-97b_73KEzYqRR7MdOD9SIqrErr-3VvEIjtcTaTzmC28fKhLdFYrdp9enZsVFUn3gHb7w4aYZIHIi6cqXZEtqfP4Rvx_A; DS=eyJhbGciOiJSUzI1NiIsImtpZCI6IlNLMmpJbnU3SWpjMkp1eFJad1psWHBZRUpQQkFvIiwidHlwIjoiSldUIn0.eyJhbXIiOlsiZW1haWwiXSwiYXV0aDBJZCI6bnVsbCwiZHJuIjoiRFMiLCJlbWFpbCI6IjMwbWVsaW5hQHJ1c3R5bG9hZC5jb20iLCJleHAiOjE3MzEzMTcxODgsImdpdmVuTmFtZSI6IiIsImlhdCI6MTcyODg5Nzk4OCwiaXNzIjoiUDJqSW50dFJNdVhweVlaTWJWY3NjNEM5WjBSVCIsImxhc3ROYW1lIjoiIiwibmFtZSI6IiIsInBpY3R1cmUiOiIiLCJyZXhwIjoiMjAyNS0xMC0xM1QwOToyNjoyOFoiLCJzdHl0Y2hJZCI6bnVsbCwic3ViIjoiVTJuUUdmUGJlZnpNemRXQnVpcDU5aDZFSU1DZSIsInRlbmFudEludml0YXRpb24iOm51bGwsInRlbmFudEludml0ZXIiOm51bGwsInVzZXJJZCI6IlUyblFHZlBiZWZ6TXpkV0J1aXA1OWg2RUlNQ2UiLCJ2ZXJpZmllZEVtYWlsIjp0cnVlfQ.GJGJoWHM3eoaEnTdTFXO73YaGGabXOrdwNmbTEvBXPbJ-C6awn8Ulx_7Si_r0nhSWgebni06rJDyVz8BJMiEkcLVUCCxgzg1Tforr5R19OVW_0mlwWUTiojYL6YZGhrC2hwQb9w_iikTsaYGC8qBv_sCO6klOQWEpqTXF-hy0ZsYOYK26jPPAR3efaKvKWpkNuAf8NhbI62ZpXS8bImIqAkOyYk_cuPlMPCuDHbmWgo42RrDisMmkIPpZvyqh-vngqt_zBqH0LwjKOGwnQh-FdVIn5TLNSBg88XBbE1PWWQoYMl6kndjMFiax0POVZP6Uab5PNM_hhQb2XOjLWPCrQ; ab.storage.deviceId.dcee0642-d796-4a7b-9e56-a0108e133b07=g%3A65cedb8b-eb9b-e70c-7730-e5f2f51226d3%7Ce%3Aundefined%7Cc%3A1728896470750%7Cl%3A1728897988682; ab.storage.userId.dcee0642-d796-4a7b-9e56-a0108e133b07=g%3AU2nQGfPbefzMzdWBuip59h6EIMCe%7Ce%3Aundefined%7Cc%3A1728897988681%7Cl%3A1728897988682; ab.storage.sessionId.dcee0642-d796-4a7b-9e56-a0108e133b07=g%3Aa5321689-baff-0d96-718d-ecdc831d5290%7Ce%3A1728899788686%7Cc%3A1728897988681%7Cl%3A1728897988686; _ga_2N7ZM9C56V=GS1.1.1728896887.1.1.1728897988.0.0.120704133; you_subscription=freemium; __cf_bm=CisDTbufy47SrFxlaYCXCreDNuWf.H2h9jKgCVzCHr8-1728897989-1.0.1.1-sL3dwybbbO6qeoShy78fei6.5vZ3SWDzwfGONBqfueBU7NzIAPkvXWAHENK.7qy5_Kb7bV2msaJ0s01gB_sSCHNB_aeed4_RbwiSmFiDLP4; _cfuvid=K0aSy8hugbR3WVaSS3Ep7EX3BR1_Vf8gkYkBE_KEfS4-1728897989527-0.0.1.1-604800000'
serverless:
  enabled: true
  disabled-gpu: true
  # 当无法找到指定的浏览器时可以在此配置路径
  # execPath: /usr/bin/microsoft-edge
  headless: new

# coze 默认配置；；；内置配置经常变动，难以维护改为配置化。新增webSdk模式，但还未得知速率是否有限制？？？
coze:
#  8k:
#    botId: 114514
#    version: 9527
#    scene: 2
#    isW: false
#  128k:
#    botId: 114514
#    version: 9527
#    scene: 2
#    isW: false
#  images:
#    botId: 114514
#    version: 9527
#    scene: 2

# 多个websdk账号可开启，用于请求计数，超过count数量该账号进入静置区
  websdk:
#    counter: 0
#    model:
#    accounts:
#    - email: xxx@gmail.com
#      password: xxx
#      validate: xxx@gmail.com

interpreter:
  baseUrl: http://127.0.0.1:7860
  echoCode: false
  ws: true

custom-llm:
  baseUrl: http://127.0.0.1:8080

# toolCall 默认配置化; 在 flags 关闭时也可用
toolCall:
  id: -1
  enabled: false
  tasks: false

# 图片放大，domain需要公网可访问的地址
# key请到https://bigjpg.com获取，每月30次免费
# 目前注册没有限制，可配置多个key轮询
#magnify:
#  - "xxx"
