# 内部转发请求配置，0值为无超时 单位为秒
# connTimeout: 用户连接超时
# idleConnTimeout: 空闲连接超时
# responseHeaderTimeout: 响应头超时
server-conn:
  connTimeout: 0
  idleConnTimeout: 0
  responseHeaderTimeout: 0

white-addr:
#  - '127.0.0.1'
#  - 'xxx.xxx.xxx.xxx'

# 开启特殊标记增强
flags: true

# 图片访问
domain: "https://chat-completion-chatgpt-adapter.hf.space"

# 内调llm，用于绘图时文本转tags
llm:
  baseUrl: "http://127.0.0.1:7860"
  model: "bing"
  token: "xxx"

# lmsys fn、 trigger
lmsys: [49 , 109]

# hf 绘图接口配置化
# 若旧接口不可用，可以到huggingface上查找同类型的接口配置
# 参数替换：{{prompt}}、{{negative_prompt}}、{{sampler}}、{{style}}、{{seed}}
hf:
#  animagine-xl-3.1:
#    baseUrl: https://boboiazumi-animagine-xl-3-1.hf.space
#    fn: [5, 61]
#    data: '[
#      "{{prompt}}",
#      "{{negative_prompt}}",
#      {{seed}},
#      1024,
#      1024,
#      8,
#      35,
#      "{{sampler}}",
#      "1024 x 1024",
#      "{{style}}",
#      "Standard v3.1",
#      true,
#      0.55,
#      1.5,
#      false,
#      false,
#      null,
#      0.65
#    ]'
#  dalle-4k:
#    baseUrl: https://mukaist-dalle-4k.hf.space
#  dalle-3-xl:
#    baseUrl: https://ehristoforu-dalle-3-xl-lora-v2.hf.space

# gemini 自定义安全设置
google:
#  safes:
#    - category: HARM_CATEGORY_HARASSMENT
#      threshold: BLOCK_NONE

bing:
  baseUrl: "https://edgeservices.bing.com/edgesvc"

claude:
  pad: 0
  cookies:
    - 'xxx1'
    - 'xxx2'

you:
  helper: 8082
  notice: "Creative Writing Mode"
  cookies:
    -  'uuid_guest=73458ab8-f026-4c35-926c-03a8543d851a; safesearch_guest=Moderate; youchat_personalization=true; youchat_smart_learn=true; _gcl_au=1.1.1802005553.1729089384; AF_DEFAULT_MEASUREMENT_STATUS=true; _ga=GA1.1.1202429570.1729089385; FPAU=1.1.1802005553.1729089384; afUserId=0835713f-b598-4e1f-980e-dc7f1ec2ab6d-p; AF_SYNC=1729089385772; daily_query_date=Thu%20Oct%2017%202024; _clck=j1lcf5%7C2%7Cfq3%7C0%7C1750; guest_has_seen_legal_disclaimer=true; daily_query_count=1; total_query_count=1; ai_model=claude_3_5_sonnet; FPLC=ks6UjJaK8slliejTdkiaqFogh7w1vf%2FgS0OhxRlXddQsSsc7A1I6ePGLEkCnVgRUdHStiLbVN6%2FH%2FjQfK8qLi3igYAxTuVNbgnbSlmLYSxwnyEwpiv278NVvpB8CCQ%3D%3D; ld_context=%7B%22kind%22%3A%22user%22%2C%22key%22%3A%2273458ab8-f026-4c35-926c-03a8543d851a%22%2C%22email%22%3A%22UNKNOWN%22%2C%22country%22%3A%22US%22%2C%22userAgent%22%3A%22Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F130.0.0.0%20Safari%2F537.36%22%2C%22secUserAgent%22%3A%22%5C%22Chromium%5C%22%3Bv%3D%5C%22130%5C%22%2C%20%5C%22Google%20Chrome%5C%22%3Bv%3D%5C%22130%5C%22%2C%20%5C%22Not%3FA_Brand%5C%22%3Bv%3D%5C%2299%5C%22%22%7D; youpro_subscription=false; _clsk=c61yai%7C1729161680215%7C11%7C0%7Cr.clarity.ms%2Fcollect; DS=eyJhbGciOiJSUzI1NiIsImtpZCI6IlNLMmpJbnU3SWpjMkp1eFJad1psWHBZRUpQQkFvIiwidHlwIjoiSldUIn0.eyJhbXIiOlsiZW1haWwiXSwiYXV0aDBJZCI6bnVsbCwiZHJuIjoiRFMiLCJlbWFpbCI6InlvdWNvbTEyMytvdDJjYndAMjkyNS5jb20iLCJleHAiOjE3MzE1ODA5ODQsImdpdmVuTmFtZSI6IiIsImlhdCI6MTcyOTE2MTc4NCwiaXNzIjoiUDJqSW50dFJNdVhweVlaTWJWY3NjNEM5WjBSVCIsImxhc3ROYW1lIjoiIiwibmFtZSI6IiIsInBpY3R1cmUiOiIiLCJyZXhwIjoiMjAyNS0xMC0xNlQxMDo0MzowNFoiLCJzdHl0Y2hJZCI6bnVsbCwic3ViIjoiVTJuWXRMdHhHM2RwdGxCZmt3dU9tTFgwVjVFMyIsInRlbmFudEludml0YXRpb24iOm51bGwsInRlbmFudEludml0ZXIiOm51bGwsInVzZXJJZCI6IlUybll0THR4RzNkcHRsQmZrd3VPbUxYMFY1RTMiLCJ2ZXJpZmllZEVtYWlsIjp0cnVlfQ.aGjS0D3eoRI1bDVFuDBHcY_smvv45fX8vMvcD_5S27wSZaNg8Opkv5hZOyBvR0Q3rWgdLjF2KgnR15hffn9hk5nYC4Rqwxg1GEakAOR6YN2-QZRaas6O6r5M5iNTPc_wQkvNXzvt9XU4W7MthThI46YUJes2w7ScX03OgzJ6N5zK0cE4-pdPOL_yN2fz2175ZVuQ7MgBnbb-lAkGgD0DJUXxzGnuQgucLI7l4NnwsNmYSnbCLokCbyI1qUXSoe9GaSTTvS0gPDX5fnA1JEtEZUUGqOxRH32aTQ2WDCb0DDNwfhnOHkfQ3wh-NnSpnSnVKUE5lKyFNmyMdEduLR8Omg; ab.storage.deviceId.dcee0642-d796-4a7b-9e56-a0108e133b07=g%3Aaea05b07-88d2-a7ec-793e-a4becc4f987b%7Ce%3Aundefined%7Cc%3A1729089382776%7Cl%3A1729161785539; ab.storage.userId.dcee0642-d796-4a7b-9e56-a0108e133b07=g%3AU2nYtLtxG3dptlBfkwuOmLX0V5E3%7Ce%3Aundefined%7Cc%3A1729161785538%7Cl%3A1729161785539; ab.storage.sessionId.dcee0642-d796-4a7b-9e56-a0108e133b07=g%3A478033c2-f911-7b9e-6dc4-25a60263912d%7Ce%3A1729163585542%7Cc%3A1729161785539%7Cl%3A1729161785542; _ga_2N7ZM9C56V=GS1.1.1729159965.4.1.1729161785.0.0.574184694; you_subscription=freemium; FPGSID=1.1729161796.1729161796.G-WYGVQX1R23.8hIcWQtM-NprGsElgOQ-Ow'

serverless:
  enabled: true
  disabled-gpu: true
# 当无法找到指定的浏览器时可以在此配置路径
# execPath: /usr/bin/microsoft-edge
  headless: new
  
# coze 默认配置；；；内置配置经常变动，难以维护改为配置化。新增webSdk模式，但还未得知速率是否有限制？？？
coze:
#  8k:
#    botId: 114514
#    version: 9527
#    scene: 2
#    isW: false
#  128k:
#    botId: 114514
#    version: 9527
#    scene: 2
#    isW: false
#  images:
#    botId: 114514
#    version: 9527
#    scene: 2

# 多个websdk账号可开启，用于请求计数，超过count数量该账号进入静置区
  websdk:
#    counter: 0
#    model:
#    accounts:
#    - email: xxx@gmail.com
#      password: xxx
#      validate: xxx@gmail.com

interpreter:
  baseUrl: http://127.0.0.1:7860
  echoCode: false
  ws: true

custom-llm:
  baseUrl: http://127.0.0.1:8080

# toolCall 默认配置化; 在 flags 关闭时也可用
toolCall:
  id: -1
  enabled: false
  tasks: false

# 图片放大，domain需要公网可访问的地址
# key请到https://bigjpg.com获取，每月30次免费
# 目前注册没有限制，可配置多个key轮询
#magnify:
#  - "xxx"
